### ISSUE TITLE
Add CI/CD for NPM publish

### ISSUE THREAD

**Issue by panchaldeep009** [excellent-react/form#4]
- [ ] Add command to publish to NPM
      - [ ] build and version bump up
      - [ ] change log generate
      - [ ] publish on npm
      
- [ ] CI/CD
       - [ ] CI should run test first
       - [ ] lib should only publish on merge to master

**Comment by ANDREYDEN** [comment]
I could give this one a shot, @panchaldeep009

**Comment by panchaldeep009** [comment]
Thanks, @ANDREYDEN

**Comment by ANDREYDEN** [comment]
This should be done with GitHub actions, right?

**Comment by panchaldeep009** [comment]
Yap, GitHub actions

**Comment by panchaldeep009** [comment]
Thanks @ANDREYDEN
